dataset_name: "Adaptation"
task: "video_mmmu_adaptation_boxed"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.videommmu_doc_to_visual_interleave
doc_to_text: !function utils.videommmu_doc_to_text_adaptation_interleave
doc_to_target: !function utils.videommmu_doc_to_answer
process_results: !function utils.videommmu_process_boxed_results
metric_list:
  - metric: mmmu_acc
    aggregation: !function utils.videommmu_aggregate_results
    higher_is_better: true
include: _default_boxed_template_yaml
