dataset_path: longvideobench/LongVideoBench
dataset_kwargs:
  token: True
  cache_dir: longvideobench
  video: True
  force_download: False
  local_files_only: False
  # From_YouTube: True
task: longvideobench_val_v_boxed
test_split: validation
doc_to_visual: !function utils.longvideobench_doc_to_visual_v
doc_to_text: !function utils.longvideobench_doc_to_text
doc_to_target: "correct_choice"
generation_kwargs:
  max_new_tokens: 16384
  temperature: 0
  do_sample: False
process_results: !function utils.longvideobench_process_boxed_results
metric_list:
  - metric: lvb_acc
    aggregation: !function utils.longvideobench_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Put your final answer in \\boxed{}."
