dataset_path: sming256/MMVU_MC
dataset_kwargs:
  token: True
  cache_dir: mmvu
  video: True
task: mmvu_val_mc
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.mmvu_doc_to_visual_val
doc_to_text: !function utils.mmvu_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false

process_results: !function utils.mmvu_process_results

metric_list:
  - metric: accuracy
    aggregation: !function utils.mmvu_aggregate_results_val
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer with the option's letter from the given choices directly."
