include: _default_boxed_template_yaml
task: mvbench_moving_direction_boxed
dataset_name: moving_direction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: moving_direction
    post_prompt: "Put your final answer in \\boxed{}."
