include: _default_boxed_template_yaml
task: mvbench_object_shuffle_boxed
dataset_name: object_shuffle
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: object_shuffle
    post_prompt: "Put your final answer in \\boxed{}."
