include: _default_boxed_template_yaml
task: mvbench_action_count_boxed
dataset_name: action_count
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_count
    post_prompt: "Put your final answer in \\boxed{}."
