include: _default_boxed_template_yaml
task: mvbench_action_sequence_boxed
dataset_name: action_sequence
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_sequence
    post_prompt: "Put your final answer in \\boxed{}."
