include: _default_boxed_template_yaml
task: mvbench_object_existence_boxed
dataset_name: object_existence
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: object_existence
    post_prompt: "Put your final answer in \\boxed{}."
