include: _default_boxed_template_yaml
task: mvbench_object_interaction_boxed
dataset_name: object_interaction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: object_interaction
    post_prompt: "Put your final answer in \\boxed{}."
