include: _default_boxed_template_yaml
task: mvbench_action_prediction_boxed
dataset_name: action_prediction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_prediction
    post_prompt: "Put your final answer in \\boxed{}."
