include: _default_boxed_template_yaml
task: mvbench_fine_grained_pose_boxed
dataset_name: fine_grained_pose
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: fine_grained_pose
    post_prompt: "Put your final answer in \\boxed{}."
