include: _default_boxed_template_yaml
task: mvbench_character_order_boxed
dataset_name: character_order
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: character_order
    post_prompt: "Put your final answer in \\boxed{}."
