include: _default_boxed_template_yaml
task: mvbench_state_change_boxed
dataset_name: state_change
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: state_change
    post_prompt: "Put your final answer in \\boxed{}."
