include: _default_boxed_template_yaml
task: mvbench_egocentric_navigation_boxed
dataset_name: egocentric_navigation
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: egocentric_navigation
    post_prompt: "Put your final answer in \\boxed{}."
