include: _default_boxed_template_yaml
task: mvbench_counterfactual_inference_boxed
dataset_name: counterfactual_inference
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: counterfactual_inference
    post_prompt: "Put your final answer in \\boxed{}."
