include: _default_boxed_template_yaml
task: mvbench_moving_count_boxed
dataset_name: moving_count
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: moving_count
    post_prompt: "Put your final answer in \\boxed{}."
