include: _default_boxed_template_yaml
task: mvbench_unexpected_action_boxed
dataset_name: unexpected_action
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: unexpected_action
    post_prompt: "Put your final answer in \\boxed{}."
