include: _default_boxed_template_yaml
task: mvbench_moving_attribute_boxed
dataset_name: moving_attribute
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: moving_attribute
    post_prompt: "Put your final answer in \\boxed{}."
