group: mvp_mini_boxed
task:
  - mvp_mini_human_object_interactions_boxed
  - mvp_mini_robot_object_interactions_boxed
  - mvp_mini_intuitive_physics_boxed
  - mvp_mini_temporal_reasoning_boxed
aggregate_metric_list:
  - aggregation: mean
    metric: pair_accuracy
    weight_by_size: false
  - aggregation: mean
    metric: single_accuracy
    weight_by_size: false
