include: _default_boxed_template_yaml
task: mvp_mini_intuitive_physics_boxed
dataset_name: intuitive_physics
test_split: mini
metric_list:
  - metric: pair_accuracy
    aggregation: !function utils.mvp_mini_ip_pair_accuracy
    higher_is_better: true
  - metric: single_accuracy
    aggregation: !function utils.mvp_single_accuracy
    higher_is_better: true
